name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*" # Trigger the workflow when a version tag is pushed

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/quill-linux-amd64 main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/quill-darwin-arm64 main.go
          GOOS=windows GOARCH=amd64 go build -o dist/quill-windows-amd64.exe main.go

      - name: Compress Binaries
        run: |
          cd dist
          zip quill-linux-amd64.zip quill-linux-amd64
          zip quill-darwin-arm64.zip quill-darwin-arm64
          zip quill-windows-amd64.zip quill-windows-amd64.exe

      - name: Generate Release Notes
        id: release-notes
        run: |
          echo "# quill ${{ github.ref_name }} 🚀" >> release-notes.md
          echo "" >> release-notes.md
          echo "## ✨ Features" >> release-notes.md
          echo "" >> release-notes.md
          echo "---" >> release-notes.md
          echo "" >> release-notes.md
          echo "## 🛠 Installation" >> release-notes.md
          echo "" >> release-notes.md
          echo "For macOS, Linux, and Windows:" >> release-notes.md
          echo "1. Download the latest release binary from the [Releases](https://github.com/tejastn10/quill/releases) page." >> release-notes.md
          echo "2. Extract the binary and add it to your system’s PATH." >> release-notes.md
          echo "" >> release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body_path: release-notes.md
          draft: false
          prerelease: false
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
